//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class meichalimEntities : DbContext
    {
        public meichalimEntities()
            : base("name=meichalimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Papertypes> tbl_Papertypes { get; set; }
        public virtual DbSet<tbl_UploadLog> tbl_UploadLog { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_items_temp> tbl_items_temp { get; set; }
        public virtual DbSet<tbl_clients> tbl_clients { get; set; }
        public virtual DbSet<tbl_clients_temp> tbl_clients_temp { get; set; }
        public virtual DbSet<tbl_items> tbl_items { get; set; }
    }
}
