//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_items
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Unitamount { get; set; }
        public Nullable<int> PalletAmount { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> Hight { get; set; }
        public Nullable<int> StockAmount { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string material { get; set; }
        public string itemType { get; set; }
        public string attribute { get; set; }
        public Nullable<int> Manufacture { get; set; }
    }
}
