//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int userNum { get; set; }
        public string UserName { get; set; }
        public Nullable<int> User_Level { get; set; }
        public string UserEmail { get; set; }
        public string password { get; set; }
    }
}
