//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UploadLog
    {
        public int LogID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UpdloadDate { get; set; }
        public Nullable<bool> Uploaded { get; set; }
        public string Remarks { get; set; }
    }
}
