//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_clients_temp
    {
        public int ClientId { get; set; }
        public string CliientName { get; set; }
        public string ClientCeditTerms { get; set; }
        public Nullable<decimal> ClientCredit { get; set; }
        public string CreditAfterChecks { get; set; }
        public string ContactPerson { get; set; }
        public string creditdays { get; set; }
        public string CreditAfterChecks1 { get; set; }
        public string AccountingBalance { get; set; }
        public string FutherChecks { get; set; }
        public string ClientType { get; set; }
    }
}
